trigger:
  branches:
    include:
      - main
      - gh-readonly-queue/*
    exclude:
      - app
      - infrastructure
  paths:
    include:
      - packer
    exclude:
      - app
      - infrastructure

resources:
  pipelines:
    - pipeline: terraform-ci
      source: Infrastructure PR

  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/heads/main

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    pool:
      name: pins-template-test
    validateName: Validate Terraform
    validationSteps:
      - script: |
          echo "=== Testing Node.js Availability on Self-Hosted Agent ==="
          echo "Current PATH: $PATH"
          echo "---"
          echo "Testing direct Node.js access..."
          node -v || echo "Node.js not found in PATH"
          npm -v || echo "NPM not found in PATH"
          echo "---"
          echo "Checking executable locations..."
          which node || echo "Node.js executable not found"
          which npm || echo "NPM executable not found"
          echo "---"
          echo "Testing NPM functionality..."
          npm --version || echo "NPM command failed"
          echo "=== Node.js Test Completed ==="
        displayName: 'Test Node.js Direct Access'
      - template: steps/terraform_format.yml@templates
      - template: steps/terraform_tflint.yml@templates
      - template: steps/run_checkov.yml@templates
      - template: steps/terraform_validate.yml@templates
        parameters:
          workingDirectory: $(Build.Repository.LocalPath)/packer/infra
