trigger:
  branches:
    include:
      - main
      - gh-readonly-queue/*
    exclude:
      - app
      - infrastructure
  paths:
    include:
      - packer
    exclude:
      - app
      - infrastructure

resources:
  pipelines:
    - pipeline: terraform-ci
      source: Infrastructure PR

  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/heads/main

stages:
  - stage: TestNodeAvailability
    displayName: 'Test Node.js Availability'
    jobs:
      - job: TestNode
        displayName: 'Test Node.js on Self-Hosted Agent'
        pool:
          name: pins-template-test
        steps:
          - script: |
              echo "Testing Node.js availability on self-hosted agent..."
              echo "Current PATH: $PATH"
              echo "---"
              node -v
              npm -v
              echo "---"
              which node
              which npm
              echo "---"
              echo "Node.js test completed successfully!"
            displayName: 'Test Node.js Direct Access'
            
          - script: |
              echo "Testing if we can run npm commands..."
              npm --version
              npm config get registry
            displayName: 'Test NPM Commands'

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    pool:
      name: pins-template-test
    validateName: Validate Terraform
    validationSteps:
      - template: steps/terraform_format.yml@templates
      - template: steps/terraform_tflint.yml@templates
      - template: steps/run_checkov.yml@templates
      - template: steps/terraform_validate.yml@templates
        parameters:
          workingDirectory: $(Build.Repository.LocalPath)/packer/infra
