trigger:
  branches:
    include:
      - main
      - gh-readonly-queue/*
    exclude:
      - app
      - infrastructure
  paths:
    include:
      - packer
    exclude:
      - app
      - infrastructure

resources:
  pipelines:
    - pipeline: terraform-ci
      source: Infrastructure PR

  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/heads/main

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    pool:
      name: pins-template-test
    validateName: Validate Terraform
    validationSteps:
      - script: |
          export NVM_DIR="/usr/local/nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use 20
          NODE_PATH=$(dirname $(nvm which 20))
          echo "##vso[task.setvariable variable=PATH]$NODE_PATH:$PATH"
          echo "✅ Using Node.js $(node -v) and NPM $(npm -v)"
          echo "✅ Node.js path set to: $NODE_PATH"
        displayName: 'Setup Node.js 20 Environment'

      - script: |
          export NVM_DIR="/usr/local/nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use 22
          NODE_PATH=$(dirname $(nvm which 22))
          echo "##vso[task.setvariable variable=PATH]$NODE_PATH:$PATH"
          echo "✅ Switched to Node.js $(node -v) and NPM $(npm -v)"
          echo "✅ Node.js 22 path set to: $NODE_PATH"
        displayName: 'Switch to Node.js 22 Environment'

      - script: |
          echo "=== Final Node.js Environment Verification ==="
          echo "Current PATH: $PATH"
          echo "---"
          echo "Node.js executable location:"
          which node
          echo "NPM executable location:"
          which npm
          echo "---"
          echo "Testing npm functionality..."
          npm --version
          npm config get registry
          echo "---"
          echo "Available Node.js versions via NVM:"
          export NVM_DIR="/usr/local/nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm list
          echo "---"
          echo "🎉 Node.js setup completed successfully without UseNode@1!"
          echo "=== Verification Completed ==="
        displayName: 'Verify Node.js Environment & PATH'

      - template: steps/terraform_format.yml@templates
      - template: steps/terraform_tflint.yml@templates
      - template: steps/run_checkov.yml@templates
      - template: steps/terraform_validate.yml@templates
        parameters:
          workingDirectory: $(Build.Repository.LocalPath)/packer/infra
