pool:
  vmImage: ubuntu-latest

trigger:
  branches:
    include:
      # trigger for merge queue branches
      - gh-readonly-queue/*

pr:
  branches:
    include:
      - '*'
  paths:
    include:
      - packer
    exclude:
      - main

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.17.0

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    pool:
      name: pins-template-test
    gitFetchDepth: 0
    globalVariables:
      - template: azure-pipelines-variables.yml@self
    validationJobs:
      - name: Check Commits
