trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.1.0

variables:
  - group: template-packer

jobs:
  - job: Build
    displayName: Build and Save Azure Scale Set Image
    steps:
      - template: steps/azure_auth.yml@templates
        parameters:
          subscriptionId: $(ODT_DEV_SUBSCRIPTION_ID)
      - script: |
          DEFAULT_TERRAFORM_VERSION=$(grep 'DEFAULT_TERRAFORM_VERSION=' $(Build.Repository.LocalPath)/packer/image-build/tools.sh | cut -d '"' -f 2)
          echo "##vso[task.setvariable variable=TERRAFORM_VERSION]$DEFAULT_TERRAFORM_VERSION"
        displayName: 'Extract DEFAULT_TERRAFORM_VERSION'
      - script: |
          packer init .
        displayName: Packer init
        workingDirectory: $(Build.Repository.LocalPath)/packer/image-build
      - script: |
          echo "TERRAFORM_VERSION: $(TERRAFORM_VERSION)"
          packer build -var "terraform_version=$(TERRAFORM_VERSION)" .
        displayName: Packer Build
        env:
          PKR_VAR_client_id: $(AZURE_SERVICE_PRINCIPAL_ID)
          PKR_VAR_client_secret: $(AZURE_SERVICE_PRINCIPAL_SECRET)
          PKR_VAR_subscription_id: $(ODT_DEV_SUBSCRIPTION_ID)
          PKR_VAR_tenant_id: $(AZURE_TENANT_ID)
          PKR_VAR_template_resource_group_name: $(templateResourceGroupName)
        workingDirectory: $(Build.Repository.LocalPath)/packer/image-build
    variables:
      templateResourceGroupName: pins-rg-template-dev
    workspace:
      clean: all
