trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  azureServiceConnection: Azure DevOps Pipelines - DevOps Template - Infrastructure DEV
  subscriptionId: 962e477c-0f3b-4372-97fc-a198a58e259e
  template_resource_group_name: pins-rg-template-dev
  build_agent_scale_set_name: pins-vmss-template-packer-dev

jobs:
  - job: Cleanup
    displayName: Delete Unused Build Agent Images
    steps:
      - task: AzurePowerShell@5
        inputs:
          ConnectedServiceNameARM: $(azureServiceConnection)
          ScriptType: 'filePath'
          ScriptPath: $(Build.Repository.LocalPath)/packer/image-build/RemoveVmssUnusedImages.ps1
          ScriptArguments: >
            -ResourceGroupName $(template_resource_group_name) `
            -VMScaleSetName $(build_agent_scale_set_name)
          errorActionPreference: stop
          FailOnStandardError: true
          TargetAzurePs: latestVersion
        displayName: 'Cleanup Older Images'
