trigger:
  branches:
    include:
      - main
      - gh-readonly-queue/*
  paths:
    include:
      - infrastructure
    exclude:
      - packer

pr:
  branches:
    include:
      - '*'
  paths:
    include:
      - infrastructure
    exclude:
      - packer

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.20.3

extends:
  template: pipelines/terraform_checks.yml@templates
  parameters:
    workingDirectory: $(Build.Repository.LocalPath)/infrastructure
    tflintConfigPath: $(Build.Repository.LocalPath)/infrastructure/.tflint.hcl
